## Sami Ahmed (PIAIC179613)

In [3]:
import numpy as np

# Additon

In [4]:
a = np.array([10,20,100,200,500])
b = np.array([3,4,5,6,7])
np.add(a, b)

array([ 13,  24, 105, 206, 507])

# Subtraction

In [5]:
a = np.array([10,20,100,200,500])
b = np.array([3,4,5,6,7])
np.subtract(a, b)

array([  7,  16,  95, 194, 493])

# Multiply

In [6]:
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])
np.multiply(a, b)

array([21, 12, 20, 30,  7])

# Divide

In [7]:
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])
np.divide(a,b)

array([2.33333333, 0.75      , 0.8       , 0.83333333, 0.14285714])

# Remainder

In [8]:
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])
np.remainder(a,b)

array([1, 3, 4, 5, 1], dtype=int32)

# Power

In [10]:
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])
np.power(a,b)

array([  343,    81,  1024, 15625,     1], dtype=int32)

# Reciprocal

In [11]:
a = np.array([7,3,4,5,1])
np.reciprocal(a)

array([0, 0, 0, 0, 1], dtype=int32)

# Absolute Values

In [12]:
a = np.array([-1, -2, 1, 2, 3, -4])
np.absolute(a)

array([1, 2, 1, 2, 3, 4])

# Median

In [14]:
a = np.array([7,3,4,5,1])
np.median(a)

4.0

# Mean

In [16]:
a = np.array([7,3,4,5,1])
np.mean(a)

4.0

# Variance Value

In [19]:
a = np.array([7,3,4,5,1])
np.var(a)

4.0

# Rounding

In [21]:
a = np.around(3.1666, 2)
a

3.17

# Square

In [24]:
arr1 = [1, 3, 4, 5]
np.square(arr1)

array([ 1,  9, 16, 25], dtype=int32)

# Square Root

In [26]:
arr = [1, 3, 4, 5]
np.sqrt(arr)

array([1.        , 1.73205081, 2.        , 2.23606798])